-- AstraTrace Migration 002: Add Vector Embeddings Table with pgvector HNSW
-- SIH 2026 | Problem ID: SIH26227

-- 1. Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create Embeddings Table
CREATE TABLE IF NOT EXISTS embeddings (
    embedding_id VARCHAR(64) PRIMARY KEY,
    tile_id VARCHAR(160) NOT NULL REFERENCES tiles(tile_id) ON DELETE CASCADE,
    scene_id VARCHAR(128) NOT NULL REFERENCES scenes(scene_id) ON DELETE CASCADE,
    model_name VARCHAR(64) NOT NULL DEFAULT 'RemoteCLIP-ViT-B-32',
    model_version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
    dimension INTEGER NOT NULL DEFAULT 512,
    embedding vector(512) NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. HNSW Cosine Similarity Vector Index
CREATE INDEX IF NOT EXISTS idx_embeddings_hnsw_cosine 
ON embeddings USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- 4. B-Tree Indexes for Relational Filtering
CREATE INDEX IF NOT EXISTS idx_embeddings_tile_id ON embeddings (tile_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_scene_id ON embeddings (scene_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_model ON embeddings (model_name, model_version);

-- 5. Documentation Comment
COMMENT ON TABLE embeddings IS 'AstraTrace 512-dimensional multimodal vision-language embeddings generated by RemoteCLIP for semantic retrieval.';
